### ISSUE TITLE
ClientBleGatt reconnection

### ISSUE THREAD

**Issue by rdeo-aziwell** [NordicSemiconductor/Kotlin-BLE-Library#36]
Unless I'm missing something, the only way to reconnect to a device after a connection is lost is to recreate a new ClientBleGatt with ClientBleGatt.connect.
This leads to very awkward code, and it could be easily avoided by providing some reconnection code that uses Android's BluetoothGatt connect method.

**Comment by philips77** [comment]
The `gatt.connect()` method which you mention has some side-effect.
Have a look at this comment: https://github.com/NordicSemiconductor/Android-BLE-Library/pull/531#issuecomment-1774902392
In Android 4.3 - 13 it was changing the value of autoConnect to *true*, while in Android 14 it was "fixed", as the Android devs forgot about the initial intention of the method.

Initially, `autoConnect` param was intended to work with bonded devices only. A connection with `autoConnect` set to *true* is also slower than with *false*, as it's offloaded to the controller which may scan with more battery-efficient parameters (Connect Indication request is sent as a response to advertising packet, so the phone needs to scan for packets from the device in order to connect). Moreover, until Android 13 where [getRemoteLeDevice(address, type)](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#getRemoteLeDevice(java.lang.String,%20int)) was added, unless the `BluetoothDevice` was scanned, in which case the address type was saved during scanning, it was assumed that the address is public ("how someone would know a random address without scanning"). This could lead to never ending connection attempt, as the scanner would wait for a device advertising with the same MAC, but a different address type. Anyway, recommendation was to connect with `autoConnect` set to *false*, and on disconnection to try calling `gatt.connect()` which was switching the flag to *true*. Of course, that was not documented anywhere, and we had to learn it the hard way.
Apparently, from Android 14 `gatt.connect()` is just reusing the same parameters as passed to `connectGatt(...)`. This of course means two different behaviors on different Android versions.

This is just a side story FYI. I'll leave the rest to Sylwester, who is the main designer of the library.

**Comment by sylwester-zielinski** [comment]
In my opinion this happens because `gatt.close()` is invoked when disconnected if `autoConnect` param is set to false.
The idea was to release resources as soon as the job is done.
Maybe we should add an configurable option to `BleGattConnectOptions` like `closeOnDisconnect`?

**Comment by sylwester-zielinski** [comment]
I created [a new issue](https://github.com/NordicSemiconductor/Kotlin-BLE-Library/issues/54) for this. We can continue there.
